---
- name: Configure WordPress Database
  hosts: webserver
  become: yes

  vars_files:
    - ../vars/main.yml

  tasks:

    - name: Install pip
      dnf:
        name: python3-pip
        state: present
    
    - name: Install Python MySQL library using pip
      pip:
        name: PyMySQL
        executable: pip3

    - name: Create WordPress database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create WordPress database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
